// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp573H4qCx2x2-M6fPqo-MMCiv5Dx-Twk',
    appId: '1:27678114092:android:34e61a8a7b4526624eac89',
    messagingSenderId: '27678114092',
    projectId: 'notes-app-7efb3',
    storageBucket: 'notes-app-7efb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMbukNTqik5dJLScBP7NTcLqOjV1B4dgI',
    appId: '1:27678114092:ios:cfc2743e32d4a1014eac89',
    messagingSenderId: '27678114092',
    projectId: 'notes-app-7efb3',
    storageBucket: 'notes-app-7efb3.firebasestorage.app',
    androidClientId: '27678114092-7vobde8te1u6jt2ihj2itccq61qprv07.apps.googleusercontent.com',
    iosClientId: '27678114092-veigh5h00h88innm94tosvusnaqb3uh6.apps.googleusercontent.com',
    iosBundleId: 'com.notes.notesApp',
  );

}